### ISSUE TITLE
Would you like to have auto-generated test reports ?

### ISSUE THREAD

**Issue by rstormsf** [OpenZeppelin/zeppelin-solidity#488]
Would you like to have auto-generated test reports ?
Example:
When Travis CI finished the job, it automatically pushes to github pages to the repo:
https://rstormsf.github.io/tokenReg_parity/mochawesome.html

Auto-deployed commit from travis: https://github.com/rstormsf/tokenReg_parity/commit/e316303f2714950b72c4ed06a9e4bb3f080644ff

Changes needed:

.travis.yml
```
deploy:
  provider: pages
  local_dir: mochawesome-report
  target_branch: gh-pages
  email: travis@ci.com
  name: Deployment Bot
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
```

truffle.js
```
  mocha: {
    reporter: 'mochawesome'
  }
```

package.json
```
yarn add mochawesome -D
```

If @maraoz or someone else can add GITHUB_TOKEN to the travis ENV vars, I can submit a PR.

Then we can always have link to the latest test suite report on README.md page like I did here:
https://github.com/rstormsf/tokenReg_parity - (click on [Full Test Report](https://rstormsf.github.io/tokenReg_parity/mochawesome.html))

Owner of the repo would also have to enable Github Pages hosting in settings
